# Generated by Django 4.0.4 on 2022-05-30 04:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='customUser',
        ),
    ]
