# Generated by Django 4.0.4 on 2022-05-30 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Home', '0002_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=100)),
                ('time', models.DateTimeField(default=None, null=True)),
                ('mid', models.CharField(max_length=100)),
            ],
        ),
    ]
