# Generated by Django 4.0.4 on 2022-05-30 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0003_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='mid',
            new_name='uid',
        ),
    ]
